"""delete_pupil_names_in_nutrition

Revision ID: c55f095bdda5
Revises: 946e631e1fd1
Create Date: 2024-02-16 00:58:33.158211

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c55f095bdda5"
down_revision: Union[str, None] = "946e631e1fd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pupil", "first_name", schema="nutrition")
    op.drop_column("pupil", "patronymic", schema="nutrition")
    op.drop_column("pupil", "last_name", schema="nutrition")
    # ### end Alembic commands ###


def downgrade() -> None:
    raise StopIteration("Нужно схлопнуть миграцию по удалению имен ученика из схеме nutrition")
