"""create_on_delete_events

Revision ID: 8d4800eab4ea
Revises: a18a13ac2a6e
Create Date: 2024-04-28 12:34:41.923098

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8d4800eab4ea"
down_revision: Union[str, None] = "a18a13ac2a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("declaration_request_class_id_fkey", "declaration", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        op.f("declaration_request_class_id_fkey"),
        "declaration",
        "request",
        ["request_class_id", "request_on_date"],
        ["class_id", "on_date"],
        source_schema="nutrition",
        referent_schema="nutrition",
        ondelete="CASCADE",
    )
    op.drop_constraint("pupil_parent_pupil_id_fkey", "pupil_parent", schema="nutrition", type_="foreignkey")
    op.drop_constraint("pupil_parent_parent_id_fkey", "pupil_parent", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        op.f("pupil_parent_parent_id_fkey"),
        "pupil_parent",
        "parent",
        ["parent_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("pupil_parent_pupil_id_fkey"),
        "pupil_parent",
        "pupil",
        ["pupil_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
        ondelete="CASCADE",
    )
    op.drop_constraint("request_class_id_fkey", "request", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        op.f("request_class_id_fkey"),
        "request",
        "school_class",
        ["class_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
        ondelete="CASCADE",
    )
    op.drop_constraint("school_class_teacher_id_fkey", "school_class", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        op.f("school_class_teacher_id_fkey"),
        "school_class",
        "teacher",
        ["teacher_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
        ondelete="SET NULL",
    )
    op.drop_constraint("session_user_id_fkey", "session", schema="user_management", type_="foreignkey")
    op.create_foreign_key(
        op.f("session_user_id_fkey"),
        "session",
        "user",
        ["user_id"],
        ["id"],
        source_schema="user_management",
        referent_schema="user_management",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("session_user_id_fkey"), "session", schema="user_management", type_="foreignkey")
    op.create_foreign_key(
        "session_user_id_fkey",
        "session",
        "user",
        ["user_id"],
        ["id"],
        source_schema="user_management",
        referent_schema="user_management",
    )
    op.drop_constraint(op.f("school_class_teacher_id_fkey"), "school_class", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        "school_class_teacher_id_fkey",
        "school_class",
        "teacher",
        ["teacher_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    op.drop_constraint(op.f("request_class_id_fkey"), "request", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        "request_class_id_fkey",
        "request",
        "school_class",
        ["class_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    op.drop_constraint(op.f("pupil_parent_pupil_id_fkey"), "pupil_parent", schema="nutrition", type_="foreignkey")
    op.drop_constraint(op.f("pupil_parent_parent_id_fkey"), "pupil_parent", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        "pupil_parent_parent_id_fkey",
        "pupil_parent",
        "parent",
        ["parent_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    op.create_foreign_key(
        "pupil_parent_pupil_id_fkey",
        "pupil_parent",
        "pupil",
        ["pupil_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    op.drop_constraint(op.f("declaration_request_class_id_fkey"), "declaration", schema="nutrition", type_="foreignkey")
    op.create_foreign_key(
        "declaration_request_class_id_fkey",
        "declaration",
        "request",
        ["request_class_id", "request_on_date"],
        ["class_id", "on_date"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    # ### end Alembic commands ###
