"""create_menu

Revision ID: 0eb2e97c9f09
Revises: b67be27d0f5d
Create Date: 2024-01-06 18:27:34.266465

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0eb2e97c9f09"
down_revision: Union[str, None] = "b67be27d0f5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("calories", sa.Numeric(scale=2), nullable=False),
        sa.Column("proteins", sa.Numeric(scale=2), nullable=False),
        sa.Column("fats", sa.Numeric(scale=2), nullable=False),
        sa.Column("carbohydrates", sa.Numeric(scale=2), nullable=False),
        sa.Column("price", sa.Numeric(scale=2), nullable=False),
        sa.Column("photo", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("food_pkey")),
        schema="nutrition",
    )
    op.create_table(
        "menu",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("school_class_type", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("menu_pkey")),
        schema="nutrition",
    )
    op.create_table(
        "breakfast_food",
        sa.Column("menu_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("food_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["nutrition.food.id"], name=op.f("breakfast_food_food_id_fkey")),
        sa.ForeignKeyConstraint(["menu_id"], ["nutrition.menu.id"], name=op.f("breakfast_food_menu_id_fkey")),
        sa.PrimaryKeyConstraint("menu_id", "food_id", name=op.f("breakfast_food_pkey")),
        schema="nutrition",
    )
    op.create_table(
        "dinner_food",
        sa.Column("menu_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("food_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["nutrition.food.id"], name=op.f("dinner_food_food_id_fkey")),
        sa.ForeignKeyConstraint(["menu_id"], ["nutrition.menu.id"], name=op.f("dinner_food_menu_id_fkey")),
        sa.PrimaryKeyConstraint("menu_id", "food_id", name=op.f("dinner_food_pkey")),
        schema="nutrition",
    )
    op.create_table(
        "snacks_food",
        sa.Column("menu_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("food_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["nutrition.food.id"], name=op.f("snacks_food_food_id_fkey")),
        sa.ForeignKeyConstraint(["menu_id"], ["nutrition.menu.id"], name=op.f("snacks_food_menu_id_fkey")),
        sa.PrimaryKeyConstraint("menu_id", "food_id", name=op.f("snacks_food_pkey")),
        schema="nutrition",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snacks_food", schema="nutrition")
    op.drop_table("dinner_food", schema="nutrition")
    op.drop_table("breakfast_food", schema="nutrition")
    op.drop_table("menu", schema="nutrition")
    op.drop_table("food", schema="nutrition")
    # ### end Alembic commands ###
