"""add_weight_column_in_food

Revision ID: c322296497f0
Revises: 0eb2e97c9f09
Create Date: 2024-01-13 13:39:12.593355

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c322296497f0"
down_revision: Union[str, None] = "0eb2e97c9f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food",
        sa.Column("weight", sa.Numeric(scale=2), server_default=sa.text("0"), nullable=False),
        schema="nutrition",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("food", "weight", schema="nutrition")
    # ### end Alembic commands ###
