"""drop_school_and_class_metadata_from_nutrition

Revision ID: a2b9eadc7fc1
Revises: c55f095bdda5
Create Date: 2024-02-16 04:06:56.371849

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a2b9eadc7fc1"
down_revision: Union[str, None] = "c55f095bdda5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school", schema="nutrition")
    op.drop_column("school_class", "teacher_id", schema="nutrition")
    op.drop_column("school_class", "number", schema="nutrition")
    op.drop_column("school_class", "literal", schema="nutrition")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "school_class",
        sa.Column("literal", sa.VARCHAR(length=1), autoincrement=False, nullable=False),
        schema="nutrition",
    )
    op.add_column(
        "school_class", sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False), schema="nutrition"
    )
    op.add_column(
        "school_class", sa.Column("teacher_id", sa.UUID(), autoincrement=False, nullable=True), schema="nutrition"
    )
    op.create_table(
        "school",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="school_pkey"),
        schema="nutrition",
    )
    # ### end Alembic commands ###
