version: "3.9"

services:
  postgres-server:
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

#  rabbitmq:
#    ports:
#      - "15672:15672"

  app:
    environment:
      SHOW_SWAGGER_UI: 'true'

    ports:
      - "8000:8000"
