version: "3.9"

services:
  app:
    build: backend
    volumes:
      - ./backend/app:/school_meal/app

  nginx:
    build:
      target: proxy
    volumes:
      - ./frontend/web/nginx:/etc/nginx/conf.d