version: "3.9"

services:
  postgres:
    build:
      context: postgres
    healthcheck:
      test: pg_isready -U ${DB_USER} -p ${DB_PORT} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /data/postgres
    command: -p ${DB_PORT}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - school_meal_nw

  app:
    build:
      context: backend
    container_name: school_meal_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DOMAIN: ${DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - school_meal_nw

  nginx:
    build:
      context: frontend/web
    container_name: school_meal_nginx
    environment:
      ORIGIN: "https://${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/school_meal
    depends_on:
      - app
    networks:
      - school_meal_nw

volumes:
  postgres_volume:

networks:
  school_meal_nw:
    name: school_meal_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/24
          gateway: 172.15.0.1