version: "3.9"

services:
  postgres:
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

  app:
    environment:
      SHOW_SWAGGER_UI: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/school_meal/app

  nginx:
    build:
      target: proxy
    volumes:
      - ./frontend/web/nginx:/etc/nginx/templates
      - ./certs:/etc/ssl/school_meal