version: "3.9"

services:
  app:
    environment:
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      GATEWAY_HOST: ${GATEWAY_HOST:-localhost}
      GATEWAY_PORT: ${GATEWAY_PORT:-80}
      MEDIA_PATH: ${MEDIA_PATH:-/media}
    volumes:
      - ./media:${MEDIA_PATH:-/media}:ro

  nginx:
    volumes:
      - ./media:/usr/share/nginx/media:ro
