version: "3.9"

services:
  app:
    build: backend
    environment:
      SHOW_SWAGGER_UI: "true"
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      GATEWAY_HOST: ${GATEWAY_HOST:-localhost}
      GATEWAY_PORT: ${GATEWAY_PORT:-80}
      GATEWAY_MEDIA_PATH: ${GATEWAY_MEDIA_PATH:-/media}
    volumes:
      - ./backend/app:/school_meal/app

  nginx:
    build:
      target: proxy
    volumes:
      - ./frontend/web/nginx:/etc/nginx/conf.d