version: "3.9"

services:
  app:
    environment:
      MEDIA_PATH: ${MEDIA_PATH:-/media}
    volumes:
      - ./media:${MEDIA_PATH:-/media}:ro

  nginx:
    volumes:
      - ./media:/usr/share/nginx/media:ro
