version: "3.9"

services:
  postgres-server:
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

#  rabbitmq:
#    ports:
#      - "15672:15672"

  app:
    environment:
      SHOW_SWAGGER_UI: "true"
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      GATEWAY_HOST: ${GATEWAY_HOST:-localhost}
      GATEWAY_PORT: ${GATEWAY_PORT:-80}
      MEDIA_PATH: ${MEDIA_PATH:-/usr/share/media}
    volumes:
      - media:${MEDIA_PATH:-/usr/share/media}
    ports:
      - "8000:8000"

volumes:
  media: