version: "3.9"

services:
  postgres-server:
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

  app:
    environment:
      SHOW_SWAGGER_UI: "true"
      MEDIA_PATH: ${MEDIA_PATH:-/media}
    volumes:
      - ./media:${MEDIA_PATH:-/media}:ro
    ports:
      - "8000:8000"

  nginx:
    volumes:
      - ./media:/usr/share/nginx/media:ro
