version: "3.4"

services:
  postgres:
    container_name: postgres
    build: postgres/
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres


volumes:
  postgres_volume:
