version: "3.9"

x-database: &database
  DB_HOST: ${DB_HOST:-postgres-server}
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME: ${DB_NAME:-school_meal}
  DB_USER: ${DB_USER:-postgres}
  DB_PASSWORD: ${DB_PASSWORD:-postgres}

x-jwt: &jwt
  JWT_SECRET: ${JWT_SECRET}

services:
  postgres-server:
    container_name: school_meal_postgres
    build: postgres
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /data/postgres
    volumes:
      - postgres_volume:/data/postgres
    networks:
      - school_meal_nw

  app:
    image: peroovy/school_meal:app-${BRANCH_TAG:-master}
    container_name: school_meal_app
    depends_on:
      postgres-server:
        condition: service_healthy
    environment:
      <<: [*database, *jwt]
    networks:
      - school_meal_nw

  web:
    container_name: school_meal_web
    build: frontend/web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./env/nginx/certs:/etc/ssl/nginx:ro
    networks:
      - school_meal_nw

volumes:
  postgres_volume:

networks:
  school_meal_nw:
    name: school_meal_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/24
          gateway: 172.15.0.1