version: "3.4"

services:
  app:
    container_name: app
    build: backend/
    command: make migrate run
    restart: always

  nginx:
    container_name: nginx
    build: nginx/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
