"""create_feedback_and_feedback_canteen_tables

Revision ID: 82afea33cffe
Revises: a3e1d19301a3
Create Date: 2023-11-07 23:55:29.382737

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "82afea33cffe"
down_revision: Union[str, None] = "a3e1d19301a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_canteen",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_canteen_pkey")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("canteen_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("text", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["canteen_id"], ["feedback_canteen.id"], name=op.f("feedback_canteen_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_table("feedback_canteen")
    # ### end Alembic commands ###
