from app.legacy.auth.db.issued_token.model import IssuedToken
from app.legacy.auth.db.password.model import Password
from app.legacy.cancel_meal_periods.db.cancel_meal_period.model import CancelMealPeriod
from app.legacy.children.db.child.model import Child
from app.legacy.meal_requests.db.declared_pupil.model import DeclaredPupil
from app.legacy.meal_requests.db.meal_request.model import MealRequest
from app.legacy.meals.db.meal.model import Meal
from app.legacy.meals.db.menu.model import Menu
from app.legacy.portions.db.food.model import Food
from app.legacy.portions.db.portion.model import Portion
from app.legacy.pupils.db.pupil.model import Pupil
from app.legacy.school_classes.db.school_class.model import SchoolClass
from app.legacy.school_classes.db.teacher.model import Teacher
from app.legacy.schools.db.school.model import School
from app.legacy.users.db.user.model import User
