export const CHILDRENS_NAME = [
  {
    id: 10,
    price: -1221,
    name: 'Ковешникова Татьяна Анатольевна',
    total: 161,
    breakfast: true,
    lunch: false,
    snack: false,
    isCheck: true,
  },
  {
    id: 11,
    price: 78,
    name: 'Шкатова Ангелина Валерьевна',
    total: 308,
    breakfast: true,
    lunch: false,
    snack: false,
    isCheck: true,
  },
  {
    id: 12,
    price: 533,
    name: 'Няшина Кристина Юрьевна',
    breakfast: false,
    lunch: true,
    snack: true,
    isCheck: true,
  },
  {
    id: 13,
    price: 566,
    name: 'Перов Юрий Евгеньевич',
    total: 308,
    breakfast: false,
    lunch: true,
    snack: false,
    isCheck: true,
  },
  {
    id: 14,
    price: 1322,
    name: 'Лыков Дмитрий Вадимович',
    total: 227,
    breakfast: true,
    lunch: false,
    snack: true,
    isCheck: true,
  },
  {
    id: 15,
    price: 100,
    name: 'Серебрякова Елена Юрьевна',
    total: 227,
    breakfast: true,
    lunch: false,
    snack: true,
    isCheck: true,
  },
  {
    id: 16,
    price: 988,
    name: 'Загуменова Марина Валерьевна',
    total: 308,
    breakfast: true,
    lunch: true,
    snack: true,
    isCheck: true,
  },
  {
    id: 17,
    price: 5,
    name: 'Алехин Андрей Максимович',
    total: 0,
    breakfast: false,
    lunch: false,
    snack: false,
    isCheck: true,
  },
  {
    id: 18,
    price: 1322,
    name: 'Павлов Андрей Кириллович',
    total: 308,
    breakfast: true,
    lunch: false,
    snack: false,
    isCheck: true,
  },
];
