"""add_portions_table

Revision ID: 9c3cab054f31
Revises: 0058839301b2
Create Date: 2023-05-10 18:27:22.896486

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "9c3cab054f31"
down_revision = "0058839301b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("components", sa.String(length=256), nullable=True),
        sa.Column("weight", sa.Numeric(scale=2), nullable=True),
        sa.Column("kcal", sa.Numeric(scale=2), nullable=True),
        sa.Column("protein", sa.Numeric(scale=2), nullable=True),
        sa.Column("fats", sa.Numeric(scale=2), nullable=True),
        sa.Column("carbs", sa.Numeric(scale=2), nullable=True),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], name=op.f("portions_food_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("portions_pkey")),
    )
    op.alter_column("foods", "photo_path", existing_type=sa.VARCHAR(length=128), nullable=True)
    op.drop_column("foods", "weight")
    op.drop_column("foods", "carbs")
    op.drop_column("foods", "protein")
    op.drop_column("foods", "fats")
    op.drop_column("foods", "components")
    op.drop_column("foods", "kcal")
    op.add_column("menu", sa.Column("portion_id", sa.Integer(), nullable=False))
    op.drop_constraint("menu_food_id_fkey", "menu", type_="foreignkey")
    op.create_foreign_key(op.f("menu_portion_id_fkey"), "menu", "portions", ["portion_id"], ["id"], ondelete="CASCADE")
    op.drop_column("menu", "food_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menu", sa.Column("food_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("menu_portion_id_fkey"), "menu", type_="foreignkey")
    op.create_foreign_key("menu_food_id_fkey", "menu", "foods", ["food_id"], ["id"], ondelete="CASCADE")
    op.drop_column("menu", "portion_id")
    op.add_column("foods", sa.Column("kcal", sa.REAL(), autoincrement=False, nullable=True))
    op.add_column("foods", sa.Column("components", sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column("foods", sa.Column("fats", sa.REAL(), autoincrement=False, nullable=True))
    op.add_column("foods", sa.Column("protein", sa.REAL(), autoincrement=False, nullable=True))
    op.add_column("foods", sa.Column("carbs", sa.REAL(), autoincrement=False, nullable=True))
    op.add_column("foods", sa.Column("weight", sa.REAL(), autoincrement=False, nullable=True))
    op.alter_column("foods", "photo_path", existing_type=sa.VARCHAR(length=128), nullable=False)
    op.drop_table("portions")
    # ### end Alembic commands ###
