"""teacher_id_field_to_creator_id_in_meal_request

Revision ID: d98a4cd8039e
Revises: 653d88706866
Create Date: 2023-05-31 17:16:54.723647

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d98a4cd8039e"
down_revision = "653d88706866"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meal_requests", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.drop_constraint("meal_requests_teacher_id_fkey", "meal_requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("meal_requests_creator_id_fkey"), "meal_requests", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("meal_requests", "teacher_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meal_requests", sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("meal_requests_creator_id_fkey"), "meal_requests", type_="foreignkey")
    op.create_foreign_key(
        "meal_requests_teacher_id_fkey", "meal_requests", "users", ["teacher_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("meal_requests", "creator_id")
    # ### end Alembic commands ###
