"""portion_has_price

Revision ID: 653d88706866
Revises: 9c3cab054f31
Create Date: 2023-05-21 21:40:22.969638

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "653d88706866"
down_revision = "9c3cab054f31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals", "dinner_price")
    op.drop_column("meals", "breakfast_price")
    op.drop_column("meals", "lunch_price")
    op.add_column("portions", sa.Column("price", sa.Numeric(scale=2), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portions", "price")
    op.add_column("meals", sa.Column("lunch_price", sa.REAL(), autoincrement=False, nullable=False, server_default="0"))
    op.add_column(
        "meals", sa.Column("breakfast_price", sa.REAL(), autoincrement=False, nullable=False, server_default="0")
    )
    op.add_column(
        "meals", sa.Column("dinner_price", sa.REAL(), autoincrement=False, nullable=False, server_default="0")
    )
    # ### end Alembic commands ###
