"""add_cancellation_periods_in_nutrition

Revision ID: a855171fd99e
Revises: e5d8782c9c6d
Create Date: 2023-11-26 06:10:13.267962

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a855171fd99e"
down_revision: Union[str, None] = "e5d8782c9c6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pupil", sa.Column("cancellation_periods", sa.JSON(), server_default="[]", nullable=False), schema="nutrition"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pupil", "cancellation_periods", schema="nutrition")
    # ### end Alembic commands ###
