"""create_children_schema

Revision ID: dbe87cc52c56
Revises: c32d5dd24f1b
Create Date: 2023-11-18 17:48:08.920540

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "dbe87cc52c56"
down_revision: Union[str, None] = "c32d5dd24f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA children")

    op.create_table(
        "parent",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("child_ids", sa.ARRAY(sa.String(), dimensions=1), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("parent_pkey")),
        schema="children",
    )
    op.create_table(
        "school",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("school_pkey")),
        schema="children",
    )
    op.create_table(
        "school_class",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("literal", sa.String(length=1), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["children.school.id"], name=op.f("school_class_school_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("school_class_pkey")),
        schema="children",
    )
    op.create_table(
        "child",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("school_class_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("meal_plan", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_class_id"], ["children.school_class.id"], name=op.f("child_school_class_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("child_pkey")),
        schema="children",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("child", schema="children")
    op.drop_table("school_class", schema="children")
    op.drop_table("school", schema="children")
    op.drop_table("parent", schema="children")

    op.execute("DROP SCHEMA children")
