"""add_teacher_in_school_class

Revision ID: cdd45b36be44
Revises: 69a74ea1b24c
Create Date: 2024-01-04 00:34:49.553410

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "cdd45b36be44"
down_revision: Union[str, None] = "69a74ea1b24c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("teacher_pkey")),
        schema="nutrition",
    )
    op.add_column(
        "school_class", sa.Column("teacher_id", postgresql.UUID(as_uuid=True), nullable=True), schema="nutrition"
    )
    op.create_foreign_key(
        op.f("school_class_teacher_id_fkey"),
        "school_class",
        "teacher",
        ["teacher_id"],
        ["id"],
        source_schema="nutrition",
        referent_schema="nutrition",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("school_class_teacher_id_fkey"), "school_class", schema="nutrition", type_="foreignkey")
    op.drop_column("school_class", "teacher_id", schema="nutrition")
    op.drop_table("teacher", schema="nutrition")
    # ### end Alembic commands ###
