"""create_request_tables

Revision ID: ed3db230074d
Revises: c322296497f0
Create Date: 2024-01-14 19:01:48.886377

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "ed3db230074d"
down_revision: Union[str, None] = "c322296497f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "draft_request",
        sa.Column("class_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("pupils", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["class_id"], ["nutrition.school_class.id"], name=op.f("draft_request_class_id_fkey")),
        sa.PrimaryKeyConstraint("class_id", "on_date", name=op.f("draft_request_pkey")),
        schema="nutrition",
    )
    op.create_table(
        "request",
        sa.Column("class_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("pupils", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["class_id"], ["nutrition.school_class.id"], name=op.f("request_class_id_fkey")),
        sa.PrimaryKeyConstraint("class_id", "on_date", name=op.f("request_pkey")),
        schema="nutrition",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request", schema="nutrition")
    op.drop_table("draft_request", schema="nutrition")
    # ### end Alembic commands ###
