from app.auth.db.issued_token.model import IssuedToken
from app.auth.db.password.model import Password
from app.children.db.parent_pupil.model import ParentPupil
from app.foods.db.food.model import Food
from app.meal_requests.db.declared_pupil.model import DeclaredPupils
from app.meal_requests.db.meal_request.model import MealRequest
from app.meals.db.meal.model import Meal
from app.meals.db.menu.model import Menu
from app.pupils.db.cancel_meal_period.model import CancelMealPeriod
from app.pupils.db.pupil.model import Pupil
from app.school_classes.db.school_class.model import SchoolClass
from app.school_classes.db.teacher.model import Teacher
from app.schools.db.school.model import School
from app.users.db.user.model import User
