name: CI

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . --build-arg PIPENV_OPTIONS="--dev" -t app

      - name: Run linters
        run: docker run app make lint

  test:
    runs-on: ubuntu-20.04
    environment: ci

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.DOT_ENV }}" > backend/.env

      - name: Build images
        run: docker-compose build --build-arg PIPENV_OPTIONS="--dev" postgres-server app

      - name: Run tests
        run: docker-compose run app make test