name: pre-production deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    environment: pre-prod

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.DOT_ENV }}" > backend/.env

      - name: Run service
        run: sudo make up
