name: pre-production deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    environment: pre-prod

    steps:
      - name: Install make
        run: sudo apt install make

      - name: Install docker
        run: sudo apt install docker.io

      - name: Install Docker Compose
        run: sudo apt install docker-compose

      - name: Add user to docker group
        run: |
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.DOT_ENV }}" > backend/.env

      - name: Run service
        run: make up
