name: pre-production deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: pre-prod

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.DOT_ENV }}" > backend/.env

      - name: Build images
        run: sudo make build

      - name: Login to registry
        run: sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images to registry
        run: sudo make push

  deploy:
    runs-on: self-hosted
    environment: pre-prod
    needs: [build]

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Create .env
        run: echo '${{ secrets.DOT_ENV }}' > backend/.env

      - name: Login to registry
        run: sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Stop service
        run: sudo make down p="--rmi all"

      - name: Run service
        run: sudo make pull up